### PR TITLE
docs(parallax): add sticky prop info

### PR DESCRIPTION
**Pull request by kindoflew**
- Adds information about the new `sticky` prop.
- Adds a "Usage Notes" section to `Parallax` to clear up some things that seem to come up often in Issues
  - scroll events are fired from the component and not `window`
  - basic usage of `scrollTo`

Only other thing would be to maybe add the new `sticky` demo to the iFrames at the bottom?

### CODE REVIEW

**Comment by joshuaellis** [comment]
> Only other thing would be to maybe add the new sticky demo to the iFrames at the bottom?

Do you want me to do that?

**Comment by kindoflew** [comment]
I can probably figure it out, just wanted to make sure it was wanted there. 

Is there some automated way to add it to the `demos` folder or should I just manually copy it from the sandboxes?

**Comment by joshuaellis** [comment]
when you run `install` it'll also run the post-install script and the `copy:spring-demos` script. This should give you all the most up to date examples in this repo for you to use 👍🏼

**Comment by kindoflew** [comment]
Cool, I got all that updated, but the styles from the sticky demo aren't playing nicely with the iFrame. I fixed it locally, but I'm pretty sure I'll have to submit a separate PR to the sandboxes in `react-spring` to fix it for real. Should I push it as is and then do the other PR?

**Comment by joshuaellis** [comment]
Sure push as is and submit the PR to the main repo, I'm thinking we should just get rid of this repo and move the whole thing into the codebase... what do you think? 🤔

**Comment by kindoflew** [comment]
It makes sense to me. I see a lot of other projects do it that way as well.

**Review by joshuaellis — APPROVED** [review]

**Comment by joshuaellis** [comment]
Yeah let's wait for this to deploy and i'll move it over, it's a proper ache to move around.

**Pull request merged**
